first commit
alexeyyS000/telegrambot pull request #1
Opened 2023-09-05 15:38 UTC by alexeyyS000

2023-09-05 18:10 UTC, swimmwatch requested changes

2023-09-05 18:10 UTC, swimmwatch commented on app/bot/commands/admin.py
> +    if message.from_user.id == admin_id:
Пользователей с правами администратора может быть несколько

2023-09-05 18:10 UTC, swimmwatch commented on app/bot/commands/admin.py
> +admin_id = AdminSettings().admin_id
Глобальные переменные зло!

2023-09-05 18:10 UTC, swimmwatch commented on app/bot/commands/admin.py
> +    keyboard = await pagination_keyboard(data)
Функция для генерации клавиатуры должна заниматься генерацией именно клавиатору, а не отправкой сообщений и т. д.

2023-09-05 18:10 UTC, swimmwatch commented on app/parser_1.py
> +        if float(i["r"]) > max_rate or float(i["r"]) < min_rate:
`float(i["r"])` можно вынести в отдельную переменную, так как несколько раз встречается в коде.

2023-09-05 18:10 UTC, swimmwatch commented on docker-compose.yaml
> +version: '3.9'
Телеграмм бота тоде нужно добавить в `docker-compose`.

2023-09-16 12:59 UTC, swimmwatch requested changes

2023-09-16 12:59 UTC, swimmwatch commented on app/bot/alerts.py
> +        )
Давай тут попробуем использовать шаблонизатор Jinja. Это позволить всю логику генерации сообщения вынести в отдельный слой отображения.

2023-09-16 12:59 UTC, swimmwatch commented on app/bot/commands/admin.py
> +    if (status is not None) and (status.admin):
Давай вынесем логику проверки того, что пользователь админ либо в middleware либо в декоратор:
1. Это позволить убрать дублирование кода, который отвечает за проверку, что ты админ;
2. Это позволить убрать лишнюю вложиность в коде.

2023-09-16 12:59 UTC, swimmwatch commented on app/bot/commands/keyboards.py
> +def pagination_keyboard(data: dict):
Давай лучще заменим `dict`, на аргументы функции: `current_page`, `prev_page`, `result` и т.д.
Так будет читабельнее. В данном случае, не понятно, что хранить в себе `data`.

2023-09-16 12:59 UTC, swimmwatch commented on app/bot/middleware.py
> +class Middleware(BaseMiddleware):
Лучше назвать более конкретнее: например, `AuthorizationMiddle` или как-то иначе

2023-09-16 12:59 UTC, swimmwatch commented on app/bot/schemas.py
> +    banned: bool = False
Для чего тут нужны Pydantic схемы?

2023-09-16 12:59 UTC, swimmwatch commented on app/parser/main.py
> +                    "date_time": datetime.utcfromtimestamp(int(i["T"]) / 1000).strftime(
Что такое `i["s"]` и `i["T"]`? Их лучше тоже вынести в отдельные переменные, чтобы повысить читабельность.

2023-09-16 12:59 UTC, swimmwatch commented on app/parser/main.py
> +    for i in data:
Переменная `i` используется для обозначения индекса в массиве. Тут лучше использовать более конкретное название: например, `record` или что-то подобное.

2023-09-22 20:02 UTC, alexeyyS000 commented on app/bot/alerts.py
> +        )
сделал

2023-09-22 20:02 UTC, alexeyyS000 commented on app/bot/commands/admin.py
> +    if (status is not None) and (status.admin):
сделал с костылями

2023-09-22 20:03 UTC, alexeyyS000 commented on app/bot/commands/keyboards.py
> +def pagination_keyboard(data: dict):
сделал

2023-09-22 20:03 UTC, alexeyyS000 commented on app/bot/middleware.py
> +class Middleware(BaseMiddleware):
сделал

2023-09-22 20:03 UTC, alexeyyS000 commented on app/bot/schemas.py
> +    banned: bool = False
убрал

2023-09-22 20:03 UTC, alexeyyS000 commented on app/parser/main.py
> +                    "date_time": datetime.utcfromtimestamp(int(i["T"]) / 1000).strftime(
сделал

2023-09-22 20:03 UTC, alexeyyS000 commented on app/parser/main.py
> +    for i in data:
исправил

2023-09-24 12:15 UTC, swimmwatch requested changes

2023-09-24 12:15 UTC, swimmwatch commented on app/bot/alerts/main.py
> +    msg = tm.render(fundings=fundings)
Я бы вынес функционал рендера текста в отдельную функцию (инициализация всех нужных штук и тд), но это на твое усмотрение.

2023-09-24 12:15 UTC, swimmwatch commented on app/bot/commands/admin.py
> +    except Exception:
Лучше обрабатывать конкретное ислючение. Потому что у тебя может произойти ситуация, что произошло деление на 0 (например), но у тебя выводиться, что пользователь уже добавлен

2023-09-24 12:15 UTC, swimmwatch commented on app/services/user.py
> +        self.instance = UserDAL(session_maker).get_one_or_none(id=user_id)
Сервис должен зависить от репозитория, а не от user_id

2023-09-24 12:15 UTC, swimmwatch commented on app/worker/app.py
> +def sand():
send

2023-09-30 08:45 UTC, swimmwatch commented on app/bot/commands/admin.py
> +        with get_user_service(id) as user:
Ранее говорил, что методы должны принимать ID пользователя, а не конструктор

2023-09-30 08:51 UTC, swimmwatch requested changes

2023-09-30 08:51 UTC, swimmwatch commented on app/bot/commands/check_user_rights.py
> +    return inner
Лучше перенеси это модуль на уровень выше и назови `decorators.py`, так как тут могут быть декораторы не только для проверки прав, а для чего-то еще.

2023-09-30 08:51 UTC, swimmwatch commented on app/bot/commands/check_user_rights.py
> +        await funk(*args)
funk -> func

2023-09-30 08:51 UTC, swimmwatch commented on app/bot/middleware.py
> +class WeekendCallbackMiddleware(BaseMiddleware):
Название middleware не соответствует реальному назначению.

2023-09-30 08:51 UTC, swimmwatch commented on app/exceptions.py
> +    pass
Данные исключения относяться к `UserService`, поэтому их стоит куда-нибудь поближе к нему перенести

2023-09-30 08:51 UTC, swimmwatch commented on app/services/user.py
> +    def __init__(self, dal, id):
Сервис должен зависить толькот от репозитория.

2023-09-30 08:51 UTC, swimmwatch commented on app/worker/app.py
> +    "sand_massage": {
send

2024-01-30 22:39 UTC, merged